### ISSUE TITLE
The last visited page is not always remembered and restored on re-launching the app

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-pwa#218]
There appears to be a small bug affecting the first page navigated to after the app is launched. If the user exits the app after reading just one article, they may find themselves returned to the landing page on re-launching the app. This may be related to the function that stores the HTML of the last-visited page.

**Comment by Jaifroid** [comment]
@washere In fact there is also a regression with the new option to fix the UI bug with secondary displays. It causes the last-visited page to be forgotten, as you observed elsewhere. If you turn this option off, you will see that the last-visited page is remembered. This is in fact a failsafe mechanism that prevents the app getting stuck in a bootloop with problematic articles: if an article caused a crash, the app reloads to the landing page instead of attempting to reload the article. However, in this case it is being triggered wrongly because it sees the display reset as equivalent to a failed load of the article. This shouldn't be hard to correct.

**Comment by washere** [comment]
Thanks @Jaifroid 
I think you are right. 
Also even if no external monitor is used, the issue happens.
I have a feeling it is to do with windows not granting access rights. They keep changing things with each Windows update that affects many apps.

As it is not an .exe but in WindowsApps, not easy to grant admin & write access for testing purposes,

This is from the properties of the running in Task_Manager:

![Screenshot 2021-12-06 185229](https://user-images.githubusercontent.com/5448047/144905197-cd3f79c7-f16a-416c-83ce-5df7aa0aba01.png)

I could be totally wrong though.
Will report if anything new.
Thanks again.

**Comment by Jaifroid** [comment]
This is internal to the app. It's a failsafe I myself put in to prevent a boot loop within the app. No need to grant admin rights! I'll fix this probably later this week, but it will take longer to get into the official release. By the way, Store app is now certified.

**Comment by washere** [comment]
Thanks, as i said this was for testing purposes, first thing i do after problems post_windows_updates.
Looking forward to fix.
Thanks for Store update too, will try.
Have a good week.
