### ISSUE TITLE
[Release] Kiwix JS PWA 2.7.2: Introducing the Origin Private File System!

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-pwa#471]
## Meet the Origin Private File System: no more permission prompts and ultra-fast archive access on Desktop and Mobile!

**_Headline feature:_ The PWA now has support for the Origin Private File System, as well as a reworked file selection experience even for legacy browsers. No more permission prompts for archives in the OPFS! It works on modern desktop and mobile browsers (Android, not yet on iOS). On Chromium (Chrome, Edge, Samsung Internet) for Android, file access is approx. 10x faster for these archives, making full-text search possible and a near-native app experience.**

***DEMO of installation and use of OPFS on Firefox for Android (please be patient while the demo loads):***

<p align="center"><img src="https://github.com/kiwix/kiwix-js-windows/raw/main/screenshots/Install-PWA_Firefox_Android.gif" width="360px" /></p>

See also:&emsp;[&ensp;[**Demo of OPFS on Chrome for Android**](https://github.com/kiwix/kiwix-js-windows/blob/main/screenshots/Demo-OPFS_Chrome_Android.md)&ensp;]

See [full changelog](https://github.com/kiwix/kiwix-js-windows/blob/master/CHANGELOG.md) for fixes and updates.

Try it out instantly at [pwa.kiwix.org](https://pwa.kiwix.org/www/index.html) (make sure it has updated to 2.7.2). On Chromium and Firefox browsers for Android, the app can be installed. On Desktop, only Chromium browsers have OS installation, but the app can be bookmarked in Firefox and will work fully offline. Chromium browsers offer a much larger OPFS quota than Firefox, which is currently limited to 10GB.

While the OPFS works in Electron and NWJS apps, there is no particular advantage to using it (because they already have fast no-permissions file access). Release packages are available for Ubuntu, Debian, Fedora, OpenSUSE, AppImage, Windows XP/Vista/7/8/10/11: https://github.com/kiwix/kiwix-js-windows/releases/tag/v2.7.2

Permalinks:
* https://kiwix.github.io/kiwix-js-pwa/app

Or, in Windows 10/11, open Command/PowerShell and type:
* `winget install kiwix.kiwixjs` (modern appx installer, 64bit) - IN CERTIFICATION
* `winget install kiwix.kiwixjs.electron` (traditional executable, 32bit and 64bit) - IN CERTIFICATION

**Comment by tomayac** [comment]
> @tomayac I thought you might be interested to know that I've added support for the OPFS in the Kiwix JS PWA. I'm really pleased with this API -- it solves many of the file access problems, particularly on Android, where file access is ~10x faster than access to the user-visible FS.

Wow, that's impressive! Would you be interested in working on a case study for developer.chrome.com with me?

> You kindly added Kiwix JS PWA to the project Fugu showcase. How can I update the entry there (https://developer.chrome.com/fugu-showcase/#kiwix) to indicate that we're showcasing the OPFS API?

Updated in the backend: https://googlechromelabs.github.io/fugu-showcase/data/#pwa.kiwix.org!www!index.html. The data will be live on the actual Fugu Showcase upon the next deploy.

> Many thanks for all your work on File System Access and OPFS. I drew heavily on the code you provide in https://web.dev/origin-private-file-system/, especially for import, export, and [direct download (with progress display) into the OPFS](https://github.com/kiwix/kiwix-js-windows/blob/main/www/js/lib/cache.js#L714).

This is incredibly smooth! Love the integration, especially the direct download from the server to the OPFS! More people need to know about this! 

![Screenshot 2023-10-09 at 13 00 12](https://github.com/kiwix/kiwix-js-windows/assets/145676/12227679-a82d-4166-a8ca-f9b8e4c78c9a)

**Comment by Jaifroid** [comment]
@tomayac Thank you for the kind comments! But it's all due to a well written and well documented API... Your DevTools extension (OPFS Explorer) was also very helpful.

Many thanks for updating the Project Fugu entry.

I'd be happy to contribute to a case study if it helps to get the API better known and used. Not sure what exactly would be involved, but (usually) all publicity is good publicity... both for the API and for the app.

Pinging @kelson42 @Popolechien who know more about the public relations side of Kiwix.

**Comment by tomayac** [comment]
Thanks for getting back positively! Could I ask you to start an email thread (reach me at tomac [AT] google . COM) with everyone interested on it and we can take it from there? Looking forward to working with you. The overall flow would be low-key collaboration on a Google Doc until you are happy, we would then hand it over to our tech writers until they are happy, and finally you would get to approve the final version with our tech writers' suggestions in before the article goes live.
